config/routes.rb
BarkingCameraClub::Application.routes.draw do
  get '/about_us', to: 'about_us#index'
  get '/gallery', to: 'gallery#index'
  get '/news', to: 'news#index'
  get '/welcome', to: 'front_page#index'
  get '/members_login', to: 'members#index', as: 'login'

  # constraints(subdomain: /admin/) do
    namespace :admin do
      get "/:selection", to: "admin_panel#index"
    end
  # end



  resource :sessions, only: %w(new create destroy)
  resources :members

  root to: "front_page#index"
end

app/models/images.rb
class Images < ActiveRecord::Base
  belongs_to :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/admin/admin_panel_controller.rb
class Admin::AdminPanelController < ApplicationController

  def index
    ap params.inspect
  end

end

app/controllers/application_controller.rb
require 'awesome_print'
class ApplicationController < ActionController::Base
  include NavGateHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :render_navigation, :flash_type ,:ap
  before_filter :make_menu


  def flash_type
    if flash[:error]
      "error"
    elsif flash[:notice]
      "notice"
    elsif flash[:alert]
      "alert"
    end
  end

end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController

  def index

  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  helper_method :current_user, :logout


  def index
    logged_in?
  end

  def show
    @member = User.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def logged_in?

      if !session[:user_id]
        redirect_to new_sessions_path
      elsif !current_user.nil?
        ap "redirection"
        redirect_to member_path(id: session[:user_id])
      end
    end

    def current_user
      @current_user ||= User.find_by_id(session[:user_id])
    end

    def logout
      redirect_to session_path, method: :destroy
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:user_id] = ""
    redirect_to login_path
  end

  def create
    user = User.find_by_email(params[:user_email])
    if !user
      redirect_to login_path, flash: { error: "Incorrect Member name or password" }
    else
      if user.password == params[:password]
        session[:user_id] = user.id
        redirect_to login_path
      else
        redirect_to login_path, flash: { error: "Incorrect Member name or password" }
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, flash: { notice: 'You have been logged out' }
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def in_admin
    return "/admin" if request.fullpath == /\/admin.*/
    ""
  end


end

app/helpers/front_page_helper.rb
module FrontPageHelper

end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/about_us/index.html.erb
<h1>AboutUs#index</h1>
<p>Find me in app/views/about_us/index.html.erb</p>

app/views/admin/admin_panel/_gallery.html.erb
_site_settings.html.erb

app/views/admin/admin_panel/_news.html.erb
_images.html.erb

app/views/admin/admin_panel/_site.html.erb
site.html.erb

app/views/admin/admin_panel/index.html.erb
<h1>admin selection</h1>
<section>
  <% render @selected %>
</section>

app/views/application/_flash.html.erb
<section class='<%= flash_type %>'>
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= flash[:error] %>
</section>

app/views/front_page/index.html.erb
<h1>Welcome</h1>

app/views/gallery/index.html.erb
gallery

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarkingCameraClub</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

    <nav>
      <%= render_navigation( class: "nav links" )  %>
    </nav>
  </body>
</html>

app/views/members/_gallery.html.erb
_gallery.html.erb

app/views/members/_login.html.erb
<h2>Please login to the site</h2>
<% if flash[:notice] || flash[:error] || flash[:alert] %>
  <%= render 'application/flash' %>
<% end %>
<%= form_tag( sessions_path, method: :post) do %>
  <%= label_tag 'user_email', 'Member Email:' %>
  <%= text_field_tag 'user_email' %>
  <%= label_tag 'password','Password:' %>
  <%= text_field_tag 'password' %>
  <%= submit_tag "Login" %>
<% end %>

app/views/members/create.html.erb
<h1>Members::Member#create</h1>
<p>Find me in app/views/members/member/create.html.erb</p>

app/views/members/destroy.html.erb
<h1>Members::Member#destroy</h1>
<p>Find me in app/views/members/member/destroy.html.erb</p>

app/views/members/edit.html.erb
<h1>Members::Member#edit</h1>
<p>Find me in app/views/members/member/edit.html.erb</p>
<section>
  <%= form_tag( member_path(id: current_user.id), method: :patch) do %>
  <% news_letter,show_images = current_user.settings.split(',').each{|s| s = s.to_b} if current_user.settings %>
    <section class='password'>
      New Password <%= password_field_tag 'password' %> <br>
      Confirm Password <%= password_field_tag 'conf_password' %>
    </section>
    <section class='identifiers'>
      Name <%= text_field_tag 'name', current_user.name %> <br>
      E-mail <%= text_field_tag 'email',current_user.email %>
    </section>
    <section class='settings'>
      Show images in gallery?(Not implemented yet):
      <% show_images ? shw_imgs = true : dnt_shw_imgs = true %>
      yes:<%= radio_button_tag 'images', true, shw_imgs %>,
      no:<%= radio_button_tag 'images', false, dnt_shw_imgs %>
      <br>
      Receive Newsletters?(Not implemented yet):
      <% news_letter ? rcv_nws = true : dnt_rcv_nws = true %>
      yes:<%= radio_button_tag 'news_letter', true, rcv_nws %>,
      no:<%= radio_button_tag 'news_letter', false, dnt_rcv_nws %>
    </section>
    <% if current_user.admin %>
      <br>
      <section class='admin-status'>
        Admin status:
        <% current_user.admin ? admin = true : not_admin = true %>
        yes:<%= radio_button_tag 'admin', true, admin %>,
        no:<%= radio_button_tag 'admin', false, not_admin%>
      </section>
    <% end %>
    <%= submit_tag "Update" %>
  <% end %>
</section>

app/views/members/index.html.erb
<h1>Members::Member#index</h1>
<p>Find me in app/views/members/member/index.html.erb</p>

<%= render 'login' %>

app/views/members/new.html.erb
<h1>Members::Member#new</h1>
<p>Find me in app/views/members/member/new.html.erb</p>

app/views/members/show.html.erb
<h1>Member infomation</h1>

Member ID: <%= @member.id %><br>
Name: <%= @member.name %><br>
E-mail: <%= @member.email %><br>
Joined at: <%= @member.created_at %><br>

<% if @member.id == current_user.id || current_user.admin%>
  <%= link_to 'Edit Member Details',edit_member_path(current_user) %>
<% end %>

app/views/members/update.html.erb
<h1>Members::Member#update</h1>
<p>Find me in app/views/members/member/update.html.erb</p>

app/views/news/index.html.erb
<h1>News#index</h1>
<p>Find me in app/views/news/index.html.erb</p>